### ISSUE TITLE
Run builds on multiple cores

### ISSUE THREAD

**Issue by theottm** [Holzhaus/sphinx-multiversion#111]
Is there an option similar to `sphinx-build --jobs N` ?

**Comment by theottm** [comment]
Yes: https://holzhaus.github.io/sphinx-multiversion/master/configuration.html#overriding-configuration-variables

**Comment by lucas-bremond** [comment]
Is (--jobs)[--define] something overridable at Sphinx configuration level? (doesn't look like it)

If so, I don't think this issue should be marked as resolved.
