### ISSUE TITLE
What is the difference to other projects?

### ISSUE THREAD

**Issue by simonsan** [Holzhaus/sphinx-multiversion#14]
Like the official project: https://github.com/sphinx-contrib/sphinxcontrib-versioning
And another implementation: https://github.com/Smile-SA/sphinx-versions

Where are the differences?

**Comment by Holzhaus** [comment]
https://holzhaus.github.io/sphinx-multiversion/master/faq.html#why-another-tool-for-versioning-sphinx-docs

**Comment by simonsan** [comment]
Thank you ;-)
