### ISSUE TITLE
No more "master" in build list

### ISSUE THREAD

**Issue by davidblaisonneau** [Holzhaus/sphinx-multiversion#16]
Hi, I am using sphinx-multiversion from master branch add from a few days, there is no more "master" version in the build list.
This is the same behavior with my smv_ parameters or using the default ones.

Any idea ? Do you have the same behaviour ?

Thanks

```
sphinx-multiversion . public
[...]
```
```
git branch
  23-xxxx
  24-yyyy
  28-zzzz
* master
```
```
ls -l public/
drwxr-xr-x 11 david david 4096 mai   29 19:03 0.0.4
drwxr-xr-x 12 david david 4096 mai   29 19:03 23-xxxx
drwxr-xr-x 11 david david 4096 mai   29 19:03 24-yyyy
drwxr-xr-x 11 david david 4096 mai   29 19:03 28-zzzz
```

**Comment by Holzhaus** [comment]
Can you post the output of `sphinx-multiversion . public --dump-metadata` and posts your settings in `conf.py`?

**Comment by davidblaisonneau** [comment]
I set those variables:
```
smv_tag_whitelist = r'^.*$'
smv_remote_whitelist = '^.*$'
smv_branch_whitelist = r'^(master)$'
smv_released_pattern = r'^tags/.*$'
```

I did not see the `Failed load config for refs/heads/master` in output. How can I give you more data ? 
I have the same behavior in my CI job, so it seems not being related to my local repo.
```
sudo rm -rf public/; sphinx-multiversion -v . public --dump-metadata
Failed load config for refs/heads/master from /tmp/tmpm02dn_z1/2b3c666f9238c222a06fd2565013ce9190c57b73/.
Failed load config for refs/remotes/origin/master from /tmp/tmpm02dn_z1/2b3c666f9238c222a06fd2565013ce9190c57b73/.
{
  "0.0.4": {
    "name": "0.0.4",
    "version": "",
    "release": "0.0.4",
    "is_released": false,
    "source": "tags",
    "creatordate": "2020-05-13 19:10:56 +0000",
    "sourcedir": "/tmp/tmpm02dn_z1/e4bdf5567729a73cfa8a02a3678ea7c27c3423a6/.",
    "outputdir": "/home/david/aaaaaa/public/0.0.4",
    "confdir": "/tmp/tmpm02dn_z1/e4bdf5567729a73cfa8a02a3678ea7c27c3423a6/.",
    "docnames": [ ... ]
  }
}
```

**Comment by Holzhaus** [comment]
Is the config in the `master` branch in the same location relativr to the git repository?

**Comment by davidblaisonneau** [comment]
Yes, in root folder.

Le ven. 29 mai 2020 à 19:36, Jan Holthuis <notifications@github.com> a
écrit :

**Comment by davidblaisonneau** [comment]
File is present and readable
```
ls -al .git/refs/heads/master
-rw-r--r-- 1 david david 41 mai   29 08:33 .git/refs/heads/master
cat .git/refs/heads/master
2b3c666f9238c222a06fd2565013ce9190c57b73
```

**Comment by Holzhaus** [comment]
If the repository is public can you give me a link? That would make it easier to debug.

Otherwise I'll try to add some more logging.

**Comment by davidblaisonneau** [comment]
Ok, I removed the try/except line 143 in main and get the solution. Another module using GitPython raises this exception. 

repo = Repo()
File "/home/david/.local/lib/python3.8/site-packages/git/repo/base.py", line 181, in __init__
raise InvalidGitRepositoryError(epath)

I close this issue, thanks for helping.

**Comment by davidblaisonneau** [comment]
-

**Comment by lucasrodes** [comment]
I am getting an `InvalidGitRepositoryError` when I run 

```
sphinx-multiversion docs docs/_build/html2
```

from the root project folder. Which file are you referencing to when you mention the try/except in "line 143", @davidblaisonneau ?
