### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by dgarcia360** [Holzhaus/sphinx-multiversion#18]
@Holzhaus thank you very much for this amazing and necessary extension!

I have been trying to compile my docs using Windows and Sphinx 2.4, but I didn't manage to achieve it. When I run the ``sphinx-multiversion``  with the option ``--dump-metadata``, the extension always returns an empty object. However, I have tested the tool also in Fedora and it worked like a charm. 

 I'd love to contribute to solving this issue. If you have any initial idea of what might be happening, please let me know!

**Comment by Holzhaus** [comment]
Hi @dgarcia360, can you check if PR #19 fixes the issue?

**Comment by dgarcia360** [comment]
@Holzhaus Sure! I will check it during the weekend.

**Comment by dgarcia360** [comment]
#19 Seems to be working fine on Windows.
