### ISSUE TITLE
No matching refs found!

### ISSUE THREAD

**Issue by lucasrodes** [Holzhaus/sphinx-multiversion#20]
Hi,
my structure is as follows:

```
- docs
  |- conf.py
  |- source (contains all .rst files)
  |- _build/html
- source_code
- tests
- README.md
...
```
this is the [link to the repo](https://github.com/lucasrodes/whatstk/tree/develop).

When I run

```
$ sphinx-build -b html . _build/html
...
```

it works, but when I run

```
$ sphinx-multiversion . _build/html
No matching refs found!
```

Any idea on what migh be happening?

Looking forward to use your tool!

**Comment by ticktronaut** [comment]
I had the same issue. The solution for me was to go to the root directory of the git repository and build from there. You might give it a shot. If you are in the docs folder of your repository do the following:

    cd ..
    sphinx-multiversion docs docs/_build/html

If you want to see which tags/branches are matched add the `--dump-metadata` flag.

**Comment by lucasrodes** [comment]
Oh, my fault. Seems to be working now. Thanks!
