### ISSUE TITLE
docstring example / plot_directive / sphinx-gallery using incorrect versions

### ISSUE THREAD

**Issue by bmcfee** [Holzhaus/sphinx-multiversion#22]
First, thanks for building this tool!  It's scratching a serious itch.

The problem that I'm running into is with sphinx-multiversion==0.2.3 (though I tried to fix it with the current dev/master and it also failed).

I use [matplotlib.sphinxext.plot_directive](https://matplotlib.org/3.1.3/devel/plot_directive.html) to generate figures from docstring example code.  These code examples change from one version to the next, so they need to be generated independently for each version.  (In case it's relevant, these are discovered by autodoc / autosummary.)

As the issue title suggests, I'm seeing incorrect docstrings for some version builds.  (E.g., my development branch is getting docstrings from several tags back.)

My hunch is that autodoc/summary is getting stuck at runtime with whatever the first build version was, rather than reloading the library at each build.  Does this sound plausible?  And if this is the case, is it possible to work around (or fix), or would a fix here go entirely counter to the "no-monkey-patching" ethos of this project?

**Comment by bmcfee** [comment]
Quick follow-up: confirmed that this is due to `autodoc` using the previously imported module rather than the version corresponding to the copied source folder.

A hacky workaround for this is to put the following at the head of `conf.py`:
```python
import sys
removals = [_ for _ in sys.modules if 'YOURPACKAGENAME' in _]
for _ in removals:
    del sys.modules[_]
```
to force a reload for each documentation build.  This combined with the usual `sys.path` [hackery](https://stackoverflow.com/a/44980548) does the trick to force the correct version loading.  This only works because the main config is reused (with some config-level patching) for each build, so it feels pretty awkward.

A better solution might be to do something like `sphinx-gallery`'s [`reset_modules`](https://sphinx-gallery.github.io/stable/configuration.html#reset-modules) config option, which lets the user (conf.py) provide either a list of modules to be reloaded, or a custom callback function to be executed in between each run.  This conceivably could accept a version or tag as a parameter, which could enable custom reset logic depending on which version is being built.

**Comment by Holzhaus** [comment]
I think it would also be possible to actually use a subprocess instead of importing and invoking the build method directly. I think the performance penality would be neglible.

**Comment by Holzhaus** [comment]
Please let me know if #28 resolves the issue.

**Comment by bmcfee** [comment]
Thanks!  This seems to work, at least in the sense of the original bug I reported.

The one problem that I'm still seeing is that the version number on each build is stuck at the latest.  (I didn't check this when testing #27, so that problem may have crept in then.)  This may be due to the way that i'm pulling version in from the imported module in conf.py, so it could be out of scope for this issue.

**Comment by Holzhaus** [comment]
That should be fixed by #30, you can check this without actually building using `--dump-metadata`.

**Comment by Holzhaus** [comment]
If your want to test both, you need to merge both branches. Please let me know if that resolves your issues.

**Comment by bmcfee** [comment]
I locally rebased #30 onto #28 and checked dump-metadata; everything looks good to me. Thanks!
