### ISSUE TITLE
[BUG] Consistently failing to find refs when not called from repo root

### ISSUE THREAD

**Issue by Griatch** [Holzhaus/sphinx-multiversion#24]
## Summary of issue 
Building with sphinx-multiversion consistently gives a `No matching refs` found error. I have also tried with the latest `master` (0.2.4) with the same result. This is a false negative caused by `file_exists` not finding the source and conf files. If disabling `file_exists` completely, the multiversion-build completes successfully. 

## Description
I have whitelisted `develop` and `master` branches with no tags. My repo structure looks like this: 

```
repo root/
     docs/ 
          Makefile
          source/ 
                conf.py
                (other documentation sources)           
```

I initialize the build from the `Makefile` in `docs/`. From the same location I run 

    sphinx-build source build/html <options> 

with no issues, but when I run 
  
    sphinx-multiversion source build/html <options> 

I consistently get the error `No matching refs found!`. 

## Debugging tried

I have traced this to the `file_exists` check in sphinx-multiversion's `git.py`. The inputs to that function at the time of error is: 

    gitroot: `/absolute/path/to/root/docs`
    refname: `refs/heads/develop` and `refs/heads/master`
    filename: `source`, `source/conf.py`

It looks like the `file_exists` calls `git cat-file` with gitroot as CWD. Current working directory doesn't appear to have any impact on the result of `git cat-file` though. The issue is that gitroot is assumed to be `.` in `main.py` and is thus not the correct gitroot in this case. The relative path to source/ and conf are not relative the correct root. Running this manually fails: 

    git cat-file -e refs/heads/develop:source 

In contrast, this line works (CWD doesn't matter).

    git cat-file -e refs/heads/develop:docs/source

## Correcting the repo root 

I tested to see if it helped to hard-code gitroot (in my case to be based off `..` instead of `.` in `main.py`). The inputs to `file_exists` then become: 

    gitroot: `/absolute/path/to/root`
    refname: `refs/heads/develop` and `refs/heads/master`
    filename: `docs/source` and `docs/source/conf.py`

Indeed, this _does_ make the system correctly pass the `file_exists` check ... 

... But then it instead fails to find the config: 

     Failed load config for refs/heads/develop from /tmp/tmpwtmsgm0x/9...743dd8/docs/source
     Failed load config for refs/heads/master from /tmp/tmpwtmsgm0x/d6...9be8fe/docs/source 
     No matching refs found!

So it seems sphinx-multiversion gets confused when CWD is not the same as the actual repo root ...

I have not explored further than this, but since this case fails where the normal `sphinx-build` succeeds, it seems this is something that should be supported. 

Finally, if I completely disable the `file_exists` check with no further changes, the docs build correctly with all versions. So the failing file-check is definitely a false negative.

**Comment by Holzhaus** [comment]
Can you verify if #26 fixes the issue for you?

**Comment by snorkman88** [comment]
> Finally, if I completely disable the file_exists check with no further changes, the docs build correctly with all versions. So the failing file-check is definitely a false negative.

It may be too late but, may I ask how did you disable this check? I am facing this issue only when running sphinx-multiversion on GHA, locally everything works fine.

**Comment by ejalaa12** [comment]
@snorkman88 did you find a solution for making this work on GHA ? I have the same error.

**Comment by Griatch** [comment]
@snorkman88 I don't recall exactly, but you need to modify the multiversion source code directly to do this. I played around at the time just to see if I could pinpoint the problem.

**Comment by ejalaa12** [comment]
I found the solution, you need to call `git fetch --all` before running `sphinx-multiversion` in the workflow. Otherwise, only the PR branch is fetched and that's the only ref that sphinx will find which won't match the pattern you have in your `conf.py`
