### ISSUE TITLE
no result when building

### ISSUE THREAD

**Issue by pirona** [Holzhaus/sphinx-multiversion#25]
Hello,

Thanks for your nice work.

I'm a beginner in sphinx so sorry if I miss obvious points.

I followed your tutorial and was waiting for any error.
Instead, I got a combo no error and and no visible result ... I' not seeing anything new in my html page.

I use Sphinx with separated source and build folder  :  docs/{source,build}
My git repo is a this level (docs)

`Running Sphinx v3.1.2
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: [new config] 3 added, 0 changed, 0 removed
reading sources... [ 33%] doc_artis/page1
reading sources... [ 66%] doc_artis/page2
reading sources... [100%] index

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 33%] doc_artis/page1
writing output... [ 66%] doc_artis/page2
writing output... [100%] index

generating indices...  genindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in build/html/3.1.
Running Sphinx v3.1.2
loading pickled environment... failed
failed: source directory has changed
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: [new config] 3 added, 0 changed, 0 removed
reading sources... [ 33%] doc_artis/page1
reading sources... [ 66%] doc_artis/page2
reading sources... [100%] index

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 33%] doc_artis/page1
writing output... [ 66%] doc_artis/page2
writing output... [100%] index

generating indices...  genindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in build/html/3.2.
Running Sphinx v3.1.2
loading pickled environment... failed
failed: source directory has changed
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: [new config] 3 added, 0 changed, 0 removed
reading sources... [ 33%] doc_artis/page1
reading sources... [ 66%] doc_artis/page2
reading sources... [100%] index

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 33%] doc_artis/page1
writing output... [ 66%] doc_artis/page2
writing output... [100%] index

generating indices...  genindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in build/html/master.`

Have you met this before ?

**Comment by pirona** [comment]
Also, I'm using the  RTD theme and using a template with this

`{% extends "page.html" %}
{% block body %}
{% if current_version and latest_version and current_version != latest_version %}
<p>
  <strong>
    {% if current_version.is_released %}
    You're reading an old version of this documentation.
    If you want up-to-date information, please have a look at <a href="{{ vpathto(latest_version.name) }}">{{latest_version.name}}</a>.
    {% else %}
    You're reading the documentation for a development version.
    For the latest released version, please have a look at <a href="{{ vpathto(latest_version.name) }}">{{latest_version.name}}</a>.
    {% endif %}
  <strong>
</p>
{% endif %}
{{ super() }}
{% endblock %}%`

**Comment by pirona** [comment]
I think the html widget is just not displayed despite the fact I followed your recommendations to use the RTD theme.

**Comment by Holzhaus** [comment]
What HTML widget? If you don't add a custom template, the HTML output will not be modified.

If you're using the RTD Themse, have a look at: https://holzhaus.github.io/sphinx-multiversion/master/templates.html#readthedocs-theme

I'll close this issue for now, as it doesn't look like a bug to me. If the issue persists, please reopen and post some more info, e. g. your config and the custom template.

**Comment by pirona** [comment]
Yes I just solved it, thanks

**Comment by likklegoat** [comment]
What was the solution for this? Followed tutorial and pages do not build with a change in navigation bar for the rtd theme.
