### ISSUE TITLE
Set current version to output to root folder.

### ISSUE THREAD

**Issue by brandonllocke** [Holzhaus/sphinx-multiversion#33]
I've not seen any clear documentation regarding how to set a main version (something like root-ref in sphinxcontrib-versioning). The software works but puts out a bunch of folders all at the same level. Like this:

```
6.1/
6.2/
6.3/
6.4/
```
Is there any way to produce output like sphinxcontrib-versioning where it copies the "current" version to the root folder so that everything can be immediately pushed to a web server without the need for any additional code? So if 6.4 was the current release it would output something like:

```
6.1/
6.2/
6.3/
6.4/
thisisa64doc.html
index.html
```

Is this something that is possible in this software or does it expect you to build something else for yourself to cause people to land on the current release? I feel like I'm missing something basic. Thank you!

**Comment by brandonllocke** [comment]
I can work around this now via an htaccess file and that may end up being a cleaner solution overall, although it requires some additional code from me in the pre-build phase.

**Comment by deepankarm** [comment]
Are there any workarounds for this? If we don't want to rely on something like `htaccess`?

**Comment by Holzhaus** [comment]
If you cannot use a server side redirect, just use a html meta redirect, e. g for the main branch:

```html
<meta http-equiv="Refresh" content="0; url='https:// example.com/main/'" />
```
