### ISSUE TITLE
sphinx-multiversion with exhale

### ISSUE THREAD

**Issue by floriantschopp** [Holzhaus/sphinx-multiversion#4]
Hi all, 
I try to use the sphinx-multiversion to create versioned documentation of [maplab](https://github.com/ethz-asl/maplab/tree/develop-docs). I want to use breathe/exhale with Doxygen to create the code API. If I understand correctly, sphinx-multiversion uses folders in `/tmp` to build separate documentation for the branches which do not work with the requirement of exhale that the containment folder needs to be a subfolder of the source. I'm getting the following error:

```
$ sphinx-multiversion docs build/html
Failed load config for refs/heads/develop from /tmp/tmp4os_u6ib/0b7a48b9813033e54a78ae157ba9ed43629f084f/docs
Failed load config for refs/tags/initial_release from /tmp/tmp4os_u6ib/63ea0c8acb669904a711817b3cb74e314ecffec7/docs
Failed load config for refs/heads/master from /tmp/tmp4os_u6ib/618a0e0154d0c6e6cd84b5ac827140b5a9b84cb0/docs
Running Sphinx v2.4.4

Configuration error:
The given `containmentFolder` [/home/spadmin/tmp/maplab_ws/src/maplab/docs/api] must be a *SUBDIRECTORY* of [/tmp/tmp4os_u6ib/f309a5e108be51a1dc1dc5b93dc64e4bf0c637b5/docs].

```

Any idea how to fix this?
Thank you!

**Comment by Holzhaus** [comment]
You probably need to override the `containmentFolder` variable on the command line to point to the correct path inside the `/tmp` directory. I'll look into exposing placeholders to do that.

By the way, making assumütions about directory paths looks like a bad design decision in exhale to me.
