### ISSUE TITLE
Source links are broken / point to wrong versions

### ISSUE THREAD

**Issue by bmcfee** [Holzhaus/sphinx-multiversion#40]
(Note: this refers to sphinx-mv 0.2.3, I haven't verified that it still exists on the dev branch)

It looks as though sphinx-multiversion is playing badly with automatically generated source code links.

Example: https://librosa.org/doc/latest/generated/librosa.pcen.html#  ; note that the header on the doc page is different from the source code link https://librosa.org/doc/latest/_modules/librosa/core/spectrum.html#pcen , which appears to come from a much older tag included in the doc build.

Similarly, the "Source code" link at the bottom of the doc page points to https://librosa.org/tmp/tmpnt58hyic/adf93050549a15c80610e7cdca9a52a72a665a5c/docs/generated/librosa-pcen-1.py , which does not exist.

Since the nature of the wrong link is so different in these two cases, I'm not sure if they're both manifestations of the same bug, or two different bugs with coincidentally similar effects.

**Comment by Holzhaus** [comment]
Can you check if it still happens with the latest version?

**Comment by bmcfee** [comment]
Sorry to take so long on responding to this issue -- it's been a busy time!

I can confirm the second issue on smv 0.2.4: source urls are propagating the temporary file paths created during build, and not the (relative) target paths that they should use.

The first issue will take me a bit more time to replicate, but i'm convinced at this point that it's a separate bug.

**Comment by bmcfee** [comment]
> The first issue will take me a bit more time to replicate, but i'm convinced at this point that it's a separate bug.

Doc build finished -- the first issue appears to have resolved in 0.2.4, and `[source]` links do now appear to be mapping onto the correct build trees.
