### ISSUE TITLE
Verbosity isn't passed through to sphinx-build

### ISSUE THREAD

**Issue by zdw** [Holzhaus/sphinx-multiversion#5]
Allow verbosity setting (multiple `-v` options) to be passed through to `sphinx-build`.

**Comment by Holzhaus** [comment]
This already works. `sphinx-multiversion` uses `parse_known_args()` and passes all other arguments on to sphinx.

Doesn't this work for you?

    sphinx-multiversion -vvv docs/ html/

**Comment by Holzhaus** [comment]
@zdw ping. Do you still have this issue?

**Comment by achamayou** [comment]
It works for me :)

**Comment by Holzhaus** [comment]
Thanks for checking, I'll close this issue then.
