### ISSUE TITLE
Do not support sphinx_rtd_theme theme

### ISSUE THREAD

**Issue by sshuair** [Holzhaus/sphinx-multiversion#67]
It seems does not support the `sphinx_rtd_theme` theme.

- sphinx_rtd_theme theme, no version picker showed up
![image](https://user-images.githubusercontent.com/5787131/105687774-d1a2a480-5f33-11eb-8eb2-eea90709d491.png)

- original theme
![image](https://user-images.githubusercontent.com/5787131/105687899-f565ea80-5f33-11eb-8454-a86bb73608da.png)

**Comment by Holzhaus** [comment]
Please read: https://holzhaus.github.io/sphinx-multiversion/master/templates.html#readthedocs-theme

It you still have issues, please reopen.
